/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#1c1b1b",
        "surface-container-high": "#2a2a2a",
        "inverse-primary": "#795900",
        "background": "#131313",
        "surface-variant": "#353534",
        "on-secondary-fixed": "#1b1b1c",
        "on-surface": "#e5e2e1",
        "secondary-fixed": "#e5e2e1",
        "outline": "#9c8f78",
        "secondary-fixed-dim": "#c8c6c5",
        "secondary-container": "#474746",
        "on-background": "#e5e2e1",
        "on-secondary-fixed-variant": "#474746",
        "error": "#ffb4ab",
        "secondary": "#c8c6c5",
        "error-container": "#93000a",
        "on-primary-fixed-variant": "#5c4300",
        "primary-fixed-dim": "#fbbc00",
        "on-tertiary-fixed-variant": "#005313",
        "surface-container": "#201f1f",
        "primary": "#ffe2ab",
        "outline-variant": "#504532",
        "on-error-container": "#ffdad6",
        "surface-bright": "#393939",
        "primary-container": "#ffbf00",
        "surface-tint": "#fbbc00",
        "on-tertiary": "#00390a",
        "on-tertiary-fixed": "#002204",
        "inverse-on-surface": "#313030",
        "tertiary-fixed-dim": "#78dc77",
        "tertiary-fixed": "#94f990",
        "surface-dim": "#131313",
        "on-secondary-container": "#b7b5b4",
        "surface-container-lowest": "#0e0e0e",
        "on-secondary": "#303030",
        "surface-container-highest": "#353534",
        "on-primary": "#402d00",
        "inverse-surface": "#e5e2e1",
        "tertiary": "#96fc93",
        "on-tertiary-container": "#006218",
        "on-error": "#690005",
        "primary-fixed": "#ffdfa0",
        "on-primary-fixed": "#261a00",
        "surface": "#131313",
        "tertiary-container": "#7bdf79",
        "on-primary-container": "#6d5000",
        "on-surface-variant": "#d4c5ab"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "container-margin": "24px",
        "gutter": "16px",
        "lg": "24px",
        "md": "16px",
        "sm": "8px",
        "unit": "4px",
        "xl": "32px",
        "xs": "4px"
      },
      fontFamily: {
        "inter": ["Inter", "sans-serif"],
        "h1": ["Inter"],
        "h3": ["Inter"],
        "body-lg": ["Inter"],
        "label-caps": ["Inter"],
        "body-sm": ["Inter"],
        "data-mono": ["monospace"],
        "h2": ["Inter"]
      },
    },
  },
  plugins: [],
}
